### ISSUE TITLE
Need to specify how to use session signalling for connection close, etc

### ISSUE THREAD

**Issue by huitema** [huitema/dnsoquic#18]
From Tom Pusateri:

> In 6.6.3, it would be nice to recommend Session Signaling TLVs over equivalent EDNS(0) options for QUIC 
> connections since you are recommending keeping the connection open and reusing it.

We already have a mention of session signaling in that session (now 5.6.3.  Idle Timeouts). But we may need some better text.

**Comment by saradickinson** [comment]
RFC8490 (DNS Session Signalling) specifically says in section 4.2 that it is only applicable to DNS-over-TCP and DNS-over-TLS. It also says it cannot be used with DNS-over-HTTPS because "because HTTP has its own mechanism for managing sessions, which is incompatible with the mechanism specified here.", which I think also applies to DNS-over-QUIC. The current mention of RFC8490 it just in the context of finding useful values for idle timeouts, I suggest we remove it to avoid any implication DSO and DoQ can mix. Also see issue #23

**Comment by huitema** [comment]
Fixed in PR #37
