### ISSUE TITLE
More robust treatment of 0-RTT

### ISSUE THREAD

**Issue by martinthomson** [huitema/dnsoquic#54]
The text on use of 0-RTT is extremely thin.  Some people have noted that 0-RTT for queries is not always as simple as this draft implies.  For instance, if a server produces different responses for load balancing in a round-robin fashion, using 0-RTT can leak information about the contents of queries if an attacker is able to execute a retry.  At a caching resolver, a query can also have a side effect in that it can result in the creation of a cache entry, which can be observed by an attacker (this is generally managed by having a replay window smaller than the minimum cache validity period).

RFC 8470 talks about different strategies for managing 0-RTT that might also apply here, such as holding responses until the handshake completes.  These should also apply to DNS.

You probably also want to talk about why you believe queries are safe to send: that is, you expect them to be side-effect free (though see above) and not state modifying.

The text should cite TLS-level requirements as well.

There is probably more than I can think of at 5am in the morning, while trying to listen to an active session.  Take some time to think about this carefully.

**Comment by huitema** [comment]
The text in section 9.1 needs work -- it actually ends with an open question. Also, that text was written for the stub to recursive case, but there are probably different issues for ADoQ and XDoQ. 

RFC 8470 introduces a "too soon" error for refusing HTTP queries that do not pass some tests at the server. I wonder whether we should have something similar in the DNS case. That's probably a question better answered on the list than on GitHub.

**Comment by huitema** [comment]
Issue #57 points out that 0-RTT is mentioned in three places: protocol specification (section 5.5), implementation requirements (section 6.5.2.  Resource Management and Idle Timeout Values) and privacy considerations (sections 9.1 and 9.2). There was a rational behind that.

1) The protocol consideration specifies the law of the land, rules that result in protocol violation if not followed.

2) The implementation considerations are meant to provide sensible guidelines to developers, in particular with those who are not too familiar with QUIC

3) The privacy considerations should explain just that, and point to existing mitigations in the document.

I suggest to reorganize this as follow:

* Revise section 5.5. explaining that in view of privacy considerations (9.1), servers may or may not decide to support 0-RTT. If they do, they MUST verify that the client only forward requests that have no side effect. (Probably list here the supported operation types.) Receiving something else in 0-RTT is a protocol violation.

* Revise section 6.5.2, maybe separate treatment of resumption and 0-RTT in separate section 6.5.3. Servers have choice to support 0-RTT or not per section 5.5; clients have choice to use resumption or not, and if using resumption to use 0-RTT or not. Point to section 9.1 and 9.2 for privacy risks associated, while explaining performance benefits.

* Revise and extend section 9.1

**Comment by huitema** [comment]
After discussion on the list, the feeling so far is that 0-RTT for QUIC is so compelling that clients and servers will still do it, even if we tell them not to. So it is better to try provide usage guidelines on how to do that safely and reliably.

Safely means minimizing two big issues: using the resumption token as an identifier for tracking clients; and, replaying initial flights of packets to cause side effects at the server an infer what names were looked at by the client. The main protections are:

1) Clients should use tickets only once, to minimize tracking by third parties
2) Privacy conscious clients should not use session resumption if their IP address or location has changed, to minimize tracking by the servers
3) Servers who can enforce single use of tickets for 0-RTT should, as doing so eliminate the risk of replaying 0-RTT and has no performance cost for clients that use tickets only once
4) All servers should use TLS parameters (obfuscated_ticket_age, ticket_age_add) to assess the delay between creation of the Client Hello at the client and the arrival at the server, and disable 0-RTT if that delay is larger than a threshold of at most 30 seconds.
5) Clients should only send "safe" requests in 0-RTT data, and servers MAY terminate connections in which 0-RTT data carries other "non safe" requests. (List of what is safe TBD, should probably only include plain queries.)

The reliability part drives other requirements:

6) Servers and clients should support session resumption and 0-RTT, because this alleviate the need to maintain long lived connections.
7) Servers should issue session resumption tickets as soon as possible after the session completes, to maximize chances that the client can use resumption and 0-RTT if a session breaks
8) Session resumption tickets should have a sufficient long life time (e.g. 6 hours), so that clients are not tempted to frequently poll the server to renew tickets

I think that text should go in the revised version of section 6.5.2 -- or the new section 6.5.3.

**Comment by martinthomson** [comment]
https://datatracker.ietf.org/doc/html/draft-ietf-dprive-early-data was also mentioned as a potential home for the generic 0-RTT considerations.

Regarding your list:  1 is in TLS already.  2 should be (see 8446bis). 3 is in TLS already. 4 is in TLS already. 5 is the new contribution of this work (or the -early-data draft).  6 is a good recommendation, but hard to mandate. 7 I think that you mean after the session is established; something that should be in TLS already, but might not be.  8 is similarly sensible, but probably doesn't need to be here.

The bit that is worth talking about more is what you might do if a server determines that a request is not safe to serve.  RFC 8470 invents a new error code for this, which DNS could probably benefit from.  Alternatively, servers could delay responses until the connection is established, at which point the connection is clearly not a replay.  That's probably not wise for queries (DoS!) but it might work for larger things, like zone transfers.

**Comment by huitema** [comment]
@martinthomson I think that the last rewrite eliminated a lot of the redundancy with TLS 1.3. It addresses the points that you made about  1 (reference to TLS 1.3 appendix), also about "3 is in TLS already. 4 is in TLS already" (text just refers to section 8 of TLS 1.3) and refrains from saying anything about sending resumption ticket as soon as possible (7) while merely making a recommendation about long enough ticket life time (8). If you agree that your comments have been addressed, please close this issue.

**Comment by martinthomson** [comment]
I'll re-review and open additional issues if I missed anything.
