### ISSUE TITLE
Clarify text on server initiated transactions

### ISSUE THREAD

**Issue by saradickinson** [huitema/dnsoquic#62]
In the IETF 111 meeting a request was made to clarify that 'the lack the support of server initiated transactions' did not mean that NOTIFY could not be done over DoQ

**Comment by huitema** [comment]
The Notify transaction is defined in RFC 1996, which is an old-style RFC describing how a "master" can notify "slaves" when the master zone has been updated, so the replicas can quickly fetch the updates.

RFC 1996 has text describing how to send the NOTIFY transaction over UDP or TCP. UDP is easy: the origin just sends UDP packets to the replica servers. I think that assume that these replica servers are listening on UDP port 53. After all, they full fledged DNS servers. The text on TCP says:

    The transport protocol used for a NOTIFY transaction will be UDP unless the master has reason to believe that TCP is necessary; for example, if a firewall has been installed between master and slave, and only TCP has been allowed; or, if the changed RR is too large to fit in a UDP/DNS datagram.

I looked in RFC 1996 for a definition of who would initiate the TCP connection. That is not clear at all. The plausible interpretation is that the origin just sets up a TCP connection to the replica server, and then sends the Notify request and awaits the Notify response. In DoQ, the equivalent of that would be having the origin act as a DoQ client, and the replica server acts as a DoQ server. Once the DoQ server has been notified of an SOA update, it can turn back, open a DoQ connection to the origin server, and request an XFR over that. I think the spec, as is, supports that behavior. We may want to add an annex explaining that.

Of course, there is another interpretation, that the replica server will set a long duration connection to the origin server, and that the origin server will occasionally "push" a NOTIFY transaction over that connection. Of course, having the server sends requests over an established connection is not hard: just let the server open streams from the server-reserved range, and push transactions on these streams. This could render DoQ completely symmetric. But if we do that, we have to worry about what happens if there is no connection available between origin and replica, and that bring back things like long duration connection, keep alive, and the like. That's a lot of overhead, with keep alive messages every 30 sec or so, and it still does not guarantee that the connection will not break...

**Comment by huitema** [comment]
Maybe we should write an annex about Notify behavior.

**Comment by martinthomson** [comment]
It seems to me like you might need a protocol extension to enable use of Notify.  An explicit note to say that Notify can't be used without an extension (not included in this package), would be enough.

**Comment by huitema** [comment]
If we are solely speaking about RFC 1996 usage, between an origin and a well controlled set of replicas, then I believe that the simple solution is to have the origin act as a client of each replica for the purpose of sending NOTIFY requests. The replicas are full-fledged servers, so the occasional connection from the server is not going to create extra load -- not much more than the occasional UDP packet carrying a Do53 NOTIFY. We do not need an extension for that.

**Comment by saradickinson** [comment]
Address in https://github.com/huitema/dnsoquic/pull/69
